openapi: '3.0.0'
info:
  title: WeChat
  description: |
    Conversations allows you to easily send messages to your customers via WeChat.

    **Channel specific pre-conditions**

    - *WeChat* : What ever

  contact:
    name: tyntec API Support
    url: http://www.tyntec.com/support
    email: support@tyntec.com
  version: '3.0'
  x-repository: https://github.com/tyntec/api-collection/blob/master/conversations
  x-major-version: v3
  x-postman-collection: postman.zip
servers:
  - url: https://api.tyntec.com/conversations/v3
security:
  - ApiKeyAuth: [ ]
paths:
  /channels/wechat:
    post:
      operationId: addWeChatChannel
      summary: create a new WeChat channel
      tags:
       - "Configuration"
      description: Create a new WeChat channel in your account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: object
                  properties:
                    weChatId: 
                     type: string
                credentials:
                  type: object
                  properties:
                    appId:
                     type: string
                    appSecret:
                     type: string
    get:
      operationId: listAllWeChatChannels
      summary: list WeChat channels
    delete:
      operationId: deleteWeChatChannel 
  /messages:
    post:
      operationId: sendMessage
      summary: Send a message
      tags:
        - "Messaging"
      description: Send messages via this path.
      requestBody:
        description: The message you would like to send
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageRequest'
            examples:
              WeChat Text:
                value:
                  from: a cool business
                  to: some number
                  channel: wechat
                  content:
                    contentType: text
                    text: hi there
                  context: my-message-reference
              WeChat Image:
                value:
                  from: a cool business
                  to: some number
                  channel: wechat
                  content:
                    contentType: image
                    image:
                      url: https://www.my.com/image
                      filename: UHUH.jpeg
                  context: my-message-reference
              WeChat Template:
                value:
                  from: a cool business
                  to: some number
                  channel: wechat
                  content:
                    contentType: template
                    template:
                      templateId: wechat-yeah!
                      components:
                        body:
                          - type: text
                            text: Z
                            variable: username
                          - type: text
                            text: 2000 â‚¬
                            variable: amount
      responses:
        202:
          description: The message is accepted by our system
          content:
            application/json:
              schema:
                $ref: '#/components/responses/MessageResponse'

        400:
          $ref: '#/components/responses/BadRequest'
        403:
          $ref: '#/components/responses/Forbidden'
        default:
          $ref: '#/components/responses/Default'
components:
  responses:
    MessageResponse:
      description: Response after the server has accepted the request
      content:
        application/problem+json:
          schema:
            $ref: 'common.yaml#/components/schemas/MessageResponse'
    Default:
      description: Default response in case of any other error. Please check the error object for details
      content:
        application/problem+json:
          schema:
            $ref: 'common.yaml#/components/schemas/Problem'
    BadRequest:
      description: The request does not match our expectations. Please check the Problems object for details
      content:
        application/problem+json:
          schema:
            $ref: 'common.yaml#/components/schemas/Problem'
          example:
            status: 400
            violations: [
              {
                field: validate.request.whatsapp.contentType,
                message: must not be empty
              }
            ]
            title: Constraint Violation
    Forbidden:
      description: You attempting to use a number that is not assigned to your account
      content:
        application/problem+json:
          schema:
            $ref: 'common.yaml#/components/schemas/Problem'
          example:
            type: https://httpstatuses.com/403
            title: Forbidden
            status: 403
  schemas:
    MessageRequest:
      type: object
      description: The message you would like to send
      required:
        - to
        - channel
        - from
      properties:
        to:
          type: string
          description: |
            The receipient of the messages
            The format depends on the specific channel
          example: "+1233423454"
        from:
          type: string
          description: |
            The sender of the messages. The format depends on the specific channel.
          example: "+1233423454"
        channel:
          type: string
          description: Channel selected for delivery.
          example: WeChat
          items:
            type: string
            enum:
              - wechat
        overrides:
          $ref: 'common.yaml#/components/schemas/MessageRequestOverrides'
        context:
          type: string
          description: Context for this particular message
          maxLength: 125
        content:
          oneOf:
            - $ref: '#/components/schemas/WeChatTextContent'
            - $ref: '#/components/schemas/WeChatImageContent'
            - $ref: '#/components/schemas/WeChatTemplateContent'
      example:
        to: "+123234234"
        from: "545345345"
        channel:  "whatsapp"
        whatsapp:
          contentType: text
          text: A simple text message
    WeChatTextContent:
      type: object
      properties:
        contentType:
          type: string
          enum:
            - text
        text:
          type: string
          maxLength: 3000
    WeChatImageContent:
      type: object
      properties:
        contentType:
          type: string
          enum:
            - image
        image:
          $ref: '#/components/schemas/WeChatImage'
    WeChatTemplateContent:
      type: object
      properties:
        contentType:
          type: string
          enum:
            - template
        template:
          $ref: '#/components/schemas/WeChatTemplate'
    WeChatImage:
      type: object
      properties:
        url:
          type: string
        filename:
          type: string
    WeChatTemplate:
      type: object
      properties:
        templateId:
          type: string
        components:
          $ref: '#/components/schemas/WeChatTemplateComponents'
    WeChatTemplateComponents:
      type: object
      properties:
        body:
          type: array
          items:
            $ref: '#/components/schemas/WeChatTemplateTextBody'
    WeChatTemplateTextBody:
      type: object
      properties:
        type:
          type: string
          enum:
            - text
        text:
          type: string
        variable:
          type: string
