openapi: '3.0.0'
info:
  title: WhatsApp
  description: |
    Conversations allows you to easily send messages to your customers via  WhatsApp

    **Channel specific pre-conditions**

    - *WhatsApp* : A WhatsApp Business Account is required in order to use this channel. Please [request access here](https://www.tyntec.com/form-whatsapp-setup-your-waba)


  contact:
    name: tyntec API Support
    url: http://www.tyntec.com/support
    email: support@tyntec.com
  version: '3.0'
  x-repository: https://github.com/tyntec/api-collection/blob/master/conversations
  x-major-version: v3
  x-postman-collection: postman.zip
servers:
  - url: https://api.tyntec.com/conversations/v3
security:
  - ApiKeyAuth: [ ]
paths:
  /messages:
    post:
      operationId: sendMessage
      summary: Send a message
      tags:
        - "Messaging"
      description: Send messages via this path.
      requestBody:
        description: The message you would like to send
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageRequest'
            examples:
              WhatsApp Text:
                value:
                  from: a cool business
                  to: some number
                  channel: WhatsApp
                  content:
                    contentType: text
                    text: hi there
                  context: my-message-reference
              WhatsApp Image:
                value:
                  from: a cool business
                  to: some number
                  channel: WhatsApp
                  content:
                    contentType: image
                    image:
                      url: https://www.my.com/image
                      filename: UHUH.jpeg
                  context: my-message-reference
              WhatsApp Template:
                value:
                  from: a cool business
                  to: some number
                  channel: WhatsApp
                  content:
                    contentType: template
                    template:
                      templateId: WhatsApp-yeah!
                      components:
                        body:
                          - type: text
                            text: Z
                            variable: username
                          - type: text
                            text: 2000 â‚¬
                            variable: amount
      responses:
        202:
          description: The message is accepted by our system
          content:
            application/json:
              schema:
                $ref: '#/components/responses/MessageResponse'

        400:
          $ref: '#/components/responses/BadRequest'
        403:
          $ref: '#/components/responses/Forbidden'
        default:
          $ref: '#/components/responses/Default'
components:
  responses:
    MessageResponse:
      description: Response after the server has accepted the request
      content:
        application/problem+json:
          schema:
            $ref: 'common.yaml#/components/schemas/MessageResponse'
    Default:
      description: Default response in case of any other error. Please check the error object for details
      content:
        application/problem+json:
          schema:
            $ref: 'common.yaml#/components/schemas/Problem'
    BadRequest:
      description: The request does not match our expectations. Please check the Problems object for details
      content:
        application/problem+json:
          schema:
            $ref: 'common.yaml#/components/schemas/Problem'
          example:
            status: 400
            violations: [
              {
                field: validate.request.whatsapp.contentType,
                message: must not be empty
              }
            ]
            title: Constraint Violation
    Forbidden:
      description: You attempting to use a number that is not assigned to your account
      content:
        application/problem+json:
          schema:
            $ref: 'common.yaml#/components/schemas/Problem'
          example:
            type: https://httpstatuses.com/403
            title: Forbidden
            status: 403
  schemas:
    MessageRequest:
      type: object
      description: The message you would like to send
      required:
        - to
        - channel
        - from
      properties:
        to:
          type: string
          description: |
            The receipient of the messages
            The format depends on the specific channel
          example: "+1233423454"
        from:
          type: string
          description: |
            The sender of the messages. The format depends on the specific channel.
          example: "+1233423454"
        channel:
          type: string
          description: Channel selected for delivery.
          example: WhatsApp
          items:
            type: string
            enum:
              - whatsapp
        overrides:
          $ref: 'common.yaml#/components/schemas/MessageRequestOverrides'
        context:
          type: string
          description: Context for this particular message
          maxLength: 125
        content:
          oneOf:
            - $ref: '#/components/schemas/WhatsAppTextContent'
            - $ref: '#/components/schemas/WhatsAppImageContent'
            - $ref: '#/components/schemas/WhatsAppTemplateContent'
      example:
        to: "+123234234"
        from: "545345345"
        channel:  "whatsapp"
        whatsapp:
          contentType: text
          text: A simple text message
    WhatsAppTextContent:
      type: object
      properties:
        contentType:
          type: string
          enum:
            - text
        text:
          type: string
          maxLength: 3000
    WhatsAppImageContent:
      type: object
      properties:
        contentType:
          type: string
          enum:
            - image
        image:
          $ref: '#/components/schemas/WhatsAppImage'
    WhatsAppTemplateContent:
      type: object
      properties:
        contentType:
          type: string
          enum:
            - template
        template:
          $ref: '#/components/schemas/WhatsAppTemplate'
    WhatsAppImage:
      type: object
      properties:
        url:
          type: string
        filename:
          type: string
    WhatsAppTemplate:
      type: object
      properties:
        templateId:
          type: string
        language:
          type: string
        components:
          $ref: '#/components/schemas/WhatsAppTemplateComponents'
    WhatsAppTemplateComponents:
      type: object
      properties:
        header:
          type: array
          items:
            $ref: '#/components/schemas/WhatsAppTemplateTextBody'
        body:
          type: array
          items:
            $ref: '#/components/schemas/WhatsAppTemplateTextBody'
        button:
          oneOf:
            - $ref: '#/components/schemas/WhatsAppQuickReplyButtons'
            - $ref: '#/components/schemas/WhatsAppCallToActionButtons'

    WhatsAppTemplateTextBody:
      type: object
      properties:
        type:
          type: string
          enum:
            - text
        text:
          type: string
    WhatsAppTemplateButtonComponent:
      type: object
      description: Button component of a template
      required:
        - type
        - buttons
      properties:
        type:
          type: string
          description: Determines the type of the component
          enum:
            - BUTTONS
        buttons:
          oneOf:
            - $ref: '#/components/schemas/WhatsAppQuickReplyButtons'
            - $ref: '#/components/schemas/WhatsAppCallToActionButtons'
    WhatsAppQuickReplyButtons:
      type: array
      description: Quick Reply buttons
      items:
        $ref: '#/components/schemas/WhatsAppQuickReplyButton'
      minItems: 1
      maxItems: 3
    WhatsAppQuickReplyButton:
      type: object
      description: Quick reply button, when clicked the caption and the dynamic payload is returned.
      required:
        - type
        - text
      properties:
        type:
          type: string
          description: Type of this button
          enum:
            - QUICK_REPLY
          example: QUICK_REPLY
        text:
          type: string
          description: Caption of the button
          maxLength: 20
          minLength: 1
          example: I liked it!
    WhatsAppCallToActionButtons:
      type: array
      description: Call to action buttons. At most one of each button types can be used.
      items:
        anyOf:
          - $ref: '#/components/schemas/WhatsAppURLButton'
          - $ref: '#/components/schemas/WhatsAppPhoneNumberButton'
      minItems: 1
      maxItems: 2
    WhatsAppURLButton:
      type: object
      description: Call to action button that opens the specified URL when clicked
      required:
        - type
        - text
      properties:
        type:
          type: string
          description: Type of this button
          enum:
            - URL
          example: URL
        text:
          type: string
          description: Caption of the button
          maxLength: 20
          minLength: 1
          example: Your invoice
        url:
          type: string
          description: the URL that will be openend when clicking on the button. Can contain 1 parameter at the end.
          pattern: ^https?:\/\/?[\w.-]+(?:\.[\w\.-]+)+[\w\-\._~:/?#[\]@!\$&'\(\)\*\+,;=.]+(\{\{1\}\})?
          example: https://www.myservice.com/invoices/{{1}}
    WhatsAppPhoneNumberButton:
      type: object
      description: Call to action button that initiates a call when clicked
      required:
        - type
        - text
      properties:
        type:
          type: string
          description: Type of this button
          enum:
            - PHONE_NUMBER
          example: PHONE_NUMBER
        text:
          type: string
          description: Caption of this button
          maxLength: 20
          minLength: 1
          example: Call us
        phoneNumber:
          type: string
          description: Phone number that will be called when clicking on the button.
          pattern: ^\+\d{4,23}$
          example: "+4923147790813"